/**
 * Classroom Game Backend. Compatible with the existing four sheet tabs.
 * Students: student_id,last_name,first_name,nickname,display_name,period
 * Games: code,gameType,round,durationSec,countdownEndsAt,gameEndsAt,startedAt,createdAt,retired
 * Players: code,round,gameType,studentId,displayName,period,score,streak,bestStreak,correct,attempted,updatedAt
 * Runs: gameType,code,round,studentId,displayName,period,score,correct,attempted,accuracy,bestStreak,ts
 * Keep a header row in every tab. No new columns required.
 * Changes from supplied backend: idempotent final saves and start requests,
 * retired-room checks, numeric validation, and no misleading truthy "false" values.
 * Deploy as a new version of the existing Apps Script web app to retain its URL.
 */
var SHEET_STUDENTS='Students',SHEET_GAMES='Games',SHEET_PLAYERS='Players',SHEET_RUNS='Runs';
function json(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function sheet(name){var s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name);if(!s)throw new Error('Missing sheet tab: '+name);return s;}
function allRows(name){var s=sheet(name),n=s.getLastRow();return n<2?[]:s.getRange(2,1,n-1,s.getLastColumn()).getValues();}
function doGet(e){try{var p=e.parameter||{},a=p.action;if(a==='getStudent')return json(getStudent(p.id));if(a==='getGame')return json(getGame(p.code));if(a==='getPlayers')return json(getPlayers(p.code,p.round));if(a==='getLeaderboard')return json(getLeaderboard(p.gameType,p.limit,p.code,p.round));return json({error:'unknown_action'});}catch(err){return json({error:String(err.message||err)});}}
function doPost(e){try{var b=JSON.parse(e.postData.contents),actions={createGame:createGame,startRound:startRound,endRound:endRound,updatePlayer:updatePlayer,saveRun:saveRun};if(!Object.prototype.hasOwnProperty.call(actions,b.action))return json({error:'unknown_action'});return json(actions[b.action](b));}catch(err){return json({error:String(err.message||err)});}}
function withLock(fn){var lock=LockService.getScriptLock();lock.waitLock(15000);try{return fn();}finally{lock.releaseLock();}}
function numberValue(value){var n=Number(value);if(!isFinite(n)||n<0)throw new Error('invalid_number');return n;}
function normalizedCode(value){return String(value||'').trim().toUpperCase();}
function getStudent(id){var rows=allRows(SHEET_STUDENTS),text=String(id||'').trim();for(var i=0;i<rows.length;i++){if(String(rows[i][0]).trim()===text)return {found:true,studentId:text,displayName:rows[i][4]||rows[i][3]||rows[i][2],period:rows[i][5]};}return {found:false};}
function rowToGame(r){return {exists:true,code:r[0],gameType:r[1],round:Number(r[2])||0,durationSec:Number(r[3])||0,countdownEndsAt:Number(r[4])||0,gameEndsAt:Number(r[5])||0,startedAt:Number(r[6])||0,retired:r[8]===true||String(r[8]).toLowerCase()==='true'};}
function findGameRowIndex(s,code){var n=s.getLastRow();if(n<2)return -1;var rows=s.getRange(2,1,n-1,1).getValues();for(var i=0;i<rows.length;i++)if(String(rows[i][0])===normalizedCode(code))return i+2;return -1;}
function getGame(code){var s=sheet(SHEET_GAMES),i=findGameRowIndex(s,code);return i<0?{exists:false}:rowToGame(s.getRange(i,1,1,9).getValues()[0]);}
function activeRow(code){var s=sheet(SHEET_GAMES),i=findGameRowIndex(s,code);if(i<0)throw new Error('not_found');var g=rowToGame(s.getRange(i,1,1,9).getValues()[0]);if(g.retired)throw new Error('retired');return {sheet:s,index:i,game:g};}
function createGame(b){return withLock(function(){var s=sheet(SHEET_GAMES),code=normalizedCode(b.code);if(!/^[A-Z0-9]{4}$/.test(code)||!b.gameType)throw new Error('invalid_room');if(findGameRowIndex(s,code)>=0)return {error:'code_exists'};if(b.retireCode){var old=findGameRowIndex(s,b.retireCode);if(old>=0)s.getRange(old,9).setValue(true);}s.appendRow([code,String(b.gameType),0,0,0,0,0,Date.now(),false]);return {ok:true,code:code};});}
function startRound(b){return withLock(function(){var r=activeRow(b.code),g=r.game,round=numberValue(b.round),duration=numberValue(b.durationSec),countdown=numberValue(b.countdownEndsAt),end=numberValue(b.gameEndsAt);if(round===g.round&&countdown===g.countdownEndsAt&&end===g.gameEndsAt)return {ok:true};if(g.gameEndsAt>Date.now())throw new Error('round_already_running');if(round!==g.round+1||duration<15||duration>3600||Math.abs(end-countdown-duration*1000)>10)throw new Error('invalid_round');r.sheet.getRange(r.index,3,1,5).setValues([[round,duration,countdown,end,Date.now()]]);return {ok:true};});}
function endRound(b){return withLock(function(){var r=activeRow(b.code),now=Date.now();if(r.game.gameEndsAt&&r.game.gameEndsAt<=now)return {ok:true};r.sheet.getRange(r.index,5,1,2).setValues([[Math.min(r.game.countdownEndsAt,now),now]]);return {ok:true};});}
function getPlayers(code,round){var rows=allRows(SHEET_PLAYERS),out=[];for(var i=0;i<rows.length;i++){var r=rows[i];if(String(r[0])===normalizedCode(code)&&String(r[1])===String(round))out.push({studentId:String(r[3]),displayName:r[4],period:r[5],score:Number(r[6])||0,streak:Number(r[7])||0,bestStreak:Number(r[8])||0,correct:Number(r[9])||0,attempted:Number(r[10])||0});}out.sort(function(a,b){return b.score-a.score;});return out;}
function updatePlayer(b){return withLock(function(){var r=activeRow(b.code);if(String(b.gameType)!==String(r.game.gameType)||!b.studentId)throw new Error('invalid_player');var round=numberValue(b.round);if(round!==0&&round!==r.game.round)throw new Error('stale_round');var s=sheet(SHEET_PLAYERS),last=s.getLastRow(),idx=-1,rows=last<2?[]:s.getRange(2,1,last-1,4).getValues();for(var i=0;i<rows.length;i++)if(String(rows[i][0])===normalizedCode(b.code)&&String(rows[i][1])===String(round)&&String(rows[i][3])===String(b.studentId)){idx=i+2;break;}var values=[normalizedCode(b.code),round,b.gameType,String(b.studentId),b.displayName||'',b.period||'',numberValue(b.score||0),numberValue(b.streak||0),numberValue(b.bestStreak||0),numberValue(b.correct||0),numberValue(b.attempted||0),Date.now()];if(idx<0)s.appendRow(values);else s.getRange(idx,1,1,12).setValues([values]);return {ok:true};});}
function saveRun(b){return withLock(function(){
  // Check and append under the SAME lock: concurrent tabs/retries create one final result.
  var s=sheet(SHEET_RUNS),last=s.getLastRow(),rows=last<2?[]:s.getRange(2,1,last-1,4).getValues();
  for(var i=0;i<rows.length;i++)if(String(rows[i][0])===String(b.gameType)&&String(rows[i][1])===normalizedCode(b.code)&&String(rows[i][2])===String(b.round)&&String(rows[i][3])===String(b.studentId))return {ok:true,duplicate:true};
  var g=getGame(b.code);if(!g.exists||String(g.gameType)!==String(b.gameType)||!b.studentId||numberValue(b.round)<1||Number(b.round)>g.round)throw new Error('invalid_run');
  s.appendRow([b.gameType,normalizedCode(b.code),numberValue(b.round),String(b.studentId),b.displayName||'',b.period||'',numberValue(b.score||0),numberValue(b.correct||0),numberValue(b.attempted||0),numberValue(b.accuracy||0),numberValue(b.bestStreak||0),Number(b.ts)||Date.now()]);return {ok:true};
});}
function getLeaderboard(gameType,limitStr,code,round){var limit=Math.max(1,Math.min(1000,parseInt(limitStr,10)||100)),rows=allRows(SHEET_RUNS),out=[];for(var i=0;i<rows.length;i++){var r=rows[i];if(gameType&&r[0]!==gameType)continue;if(code&&String(r[1])!==normalizedCode(code))continue;if(round!==undefined&&round!==null&&round!==''&&String(r[2])!==String(round))continue;out.push({gameType:r[0],code:r[1],round:r[2],studentId:String(r[3]),displayName:r[4],period:r[5],score:Number(r[6])||0,correct:Number(r[7])||0,attempted:Number(r[8])||0,accuracy:Number(r[9])||0,bestStreak:Number(r[10])||0,ts:r[11]});}out.sort(function(a,b){return b.score-a.score;});return out.slice(0,limit);}
